apiVersion: v1
kind: Service
metadata:
  name : mongo-express-service
  namespace: mangodb
spec:
  selector:
    app: mango_express
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 300001