apiVersion: v1
kind: Namespace
metadata:
  name: mangodb
  labels:
    name: mangodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mangodb
  labels:
    app: mango_db
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mogodb-secret
                key: mongo-root-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mogodb-secret
                key: mongo-root-password
        resources:
          limits:
            cpu:100m
          requests:
            cpu: 50m
  replicas: 2
  selector:
    matchLabels:
      app: mongodb


# Also Both service and deployments can be on the same file.

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name : mongodb-service
# spec:
#   selector:
#     app: mango_db
#   ports:
#   - port: 27017
#     targetPort: 27017
#     protocol: TCP