
apiVersion: apps/v1
kind: Deployment
metadata:
  name : mongo-express-deployment
  namespace: mangodb
  lables:
    app: mongo-express
spec:
  template:
    metadata:
      labels:
        app: mongo-express-app
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mogoexpress-secrets
                  key: mongoexp-root-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mogoexpress-secrets
                    key: mongoexp-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                    configMapKeyRef:
                      name: mongodb-configmmap
                      key: database_url
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 50m
  replicas: 2
  selector:
    matchLables:
      app: mongo-express-app
    
  